-- DropForeignKey
ALTER TABLE `abonos` DROP FOREIGN KEY `ABONOS_ID_CUENTA_fkey`;

-- DropForeignKey
ALTER TABLE `cuentas` DROP FOREIGN KEY `CUENTAS_ID_CLIENTE_fkey`;

-- DropForeignKey
ALTER TABLE `detalles_factura` DROP FOREIGN KEY `DETALLES_FACTURA_ID_FACTURA_fkey`;

-- DropForeignKey
ALTER TABLE `detalles_factura` DROP FOREIGN KEY `DETALLES_FACTURA_ID_RAZON_fkey`;

-- DropForeignKey
ALTER TABLE `detalles_medidor` DROP FOREIGN KEY `DETALLES_MEDIDOR_ID_MEDIDOR_fkey`;

-- DropForeignKey
ALTER TABLE `facturas` DROP FOREIGN KEY `FACTURAS_ID_CLIENTE_fkey`;

-- DropForeignKey
ALTER TABLE `facturas` DROP FOREIGN KEY `FACTURAS_ID_MEDIDOR_fkey`;

-- DropForeignKey
ALTER TABLE `facturas` DROP FOREIGN KEY `FACTURAS_ID_SUCURSAL_fkey`;

-- DropForeignKey
ALTER TABLE `facturas` DROP FOREIGN KEY `FACTURAS_ID_USUARIO_fkey`;

-- DropForeignKey
ALTER TABLE `medidores` DROP FOREIGN KEY `MEDIDORES_ID_CLIENTE_fkey`;

-- CreateTable
CREATE TABLE `CONCEPTOS` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CODIGO` VARCHAR(32) NOT NULL,
    `COD_INTERNO` VARCHAR(32) NULL,
    `DESCRIPCION` VARCHAR(255) NOT NULL,
    `PRECIO_BASE` DECIMAL(10, 2) NULL,
    `REQUIERE_MES` BOOLEAN NOT NULL DEFAULT false,
    `ESTADO` BOOLEAN NOT NULL DEFAULT true,
    `FECHA_CREACION` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `CODIGO`(`CODIGO`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LiquidacionCompra` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `fechaEmision` VARCHAR(191) NOT NULL,
    `dirEstablecimiento` VARCHAR(191) NOT NULL,
    `tipoIdentificacionProveedor` VARCHAR(191) NOT NULL,
    `razonSocialProveedor` VARCHAR(191) NOT NULL,
    `identificacionProveedor` VARCHAR(191) NOT NULL,
    `totalSinImpuestos` DOUBLE NOT NULL,
    `totalDescuento` DOUBLE NOT NULL,
    `importeTotal` DOUBLE NOT NULL,
    `moneda` VARCHAR(191) NOT NULL,
    `xml` LONGTEXT NULL,
    `accessKey` VARCHAR(191) NULL,
    `estadoSri` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DetalleLiquidacion` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `codigoPrincipal` VARCHAR(191) NOT NULL,
    `codigoAuxiliar` VARCHAR(191) NULL,
    `descripcion` VARCHAR(191) NOT NULL,
    `unidadMedida` VARCHAR(191) NULL,
    `cantidad` DOUBLE NOT NULL,
    `precioUnitario` DOUBLE NOT NULL,
    `descuento` DOUBLE NOT NULL,
    `precioTotalSinImpuesto` DOUBLE NOT NULL,
    `codigoImpuesto` VARCHAR(191) NOT NULL,
    `codigoPorcentajeImpuesto` VARCHAR(191) NOT NULL,
    `tarifaImpuesto` DOUBLE NOT NULL,
    `baseImponible` DOUBLE NOT NULL,
    `valorImpuesto` DOUBLE NOT NULL,
    `liquidacionId` INTEGER NOT NULL,

    INDEX `DetalleLiquidacion_liquidacionId_idx`(`liquidacionId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `CUENTAS` ADD CONSTRAINT `CUENTAS_ID_CLIENTE_fkey` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTES`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ABONOS` ADD CONSTRAINT `ABONOS_ID_CUENTA_fkey` FOREIGN KEY (`ID_CUENTA`) REFERENCES `CUENTAS`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MEDIDORES` ADD CONSTRAINT `MEDIDORES_ID_CLIENTE_fkey` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTES`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DETALLES_MEDIDOR` ADD CONSTRAINT `DETALLES_MEDIDOR_ID_MEDIDOR_fkey` FOREIGN KEY (`ID_MEDIDOR`) REFERENCES `MEDIDORES`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FACTURAS` ADD CONSTRAINT `FACTURAS_ID_CLIENTE_fkey` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTES`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FACTURAS` ADD CONSTRAINT `FACTURAS_ID_MEDIDOR_fkey` FOREIGN KEY (`ID_MEDIDOR`) REFERENCES `MEDIDORES`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FACTURAS` ADD CONSTRAINT `FACTURAS_ID_SUCURSAL_fkey` FOREIGN KEY (`ID_SUCURSAL`) REFERENCES `SUCURSALES`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FACTURAS` ADD CONSTRAINT `FACTURAS_ID_USUARIO_fkey` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIOS`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DETALLES_FACTURA` ADD CONSTRAINT `DETALLES_FACTURA_ID_FACTURA_fkey` FOREIGN KEY (`ID_FACTURA`) REFERENCES `FACTURAS`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DETALLES_FACTURA` ADD CONSTRAINT `DETALLES_FACTURA_ID_RAZON_fkey` FOREIGN KEY (`ID_RAZON`) REFERENCES `RAZONES`(`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DetalleLiquidacion` ADD CONSTRAINT `DetalleLiquidacion_liquidacionId_fkey` FOREIGN KEY (`liquidacionId`) REFERENCES `LiquidacionCompra`(`id`) ON DELETE NO ACTION ON UPDATE CASCADE;
