-- CreateEnum
CREATE TYPE "ROL" AS ENUM ('CONTADOR', 'TESORERO', 'ADMIN');

-- CreateEnum
CREATE TYPE "ESTADO_FACTURA" AS ENUM ('AUTORIZADO', 'ELIMINADO', 'SIN_AUTORIZAR');

-- CreateEnum
CREATE TYPE "TIPO_PAGO" AS ENUM ('EFECTIVO', 'CREDITO', 'DEPOSITO', 'CHEQUE');

-- CreateTable
CREATE TABLE "usuarios" (
    "ID" SERIAL NOT NULL,
    "CEDULA" TEXT NOT NULL,
    "NOMBRE" TEXT NOT NULL,
    "APELLIDO" TEXT NOT NULL,
    "CORREO" TEXT NOT NULL,
    "HASH" TEXT NOT NULL,
    "SALT" TEXT NOT NULL,
    "ROL" "ROL" NOT NULL DEFAULT 'CONTADOR',
    "ESTADO" BOOLEAN NOT NULL DEFAULT true,
    "FECHA_CREACION" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "usuarios_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "clientes" (
    "ID" SERIAL NOT NULL,
    "IDENTIFICACION" TEXT NOT NULL,
    "RAZON_SOCIAL" TEXT NOT NULL,
    "NOMBRE_COMERCIAL" TEXT,
    "DIRECCION" TEXT NOT NULL,
    "TELEFONO1" TEXT NOT NULL,
    "TELEFONO2" TEXT,
    "CORREO" TEXT DEFAULT 'tiolucasoswaldo1967@gmail.com',
    "TARIFA" TEXT,
    "GRUPO" TEXT,
    "ZONA" TEXT,
    "RUTA" TEXT,
    "VENDEDOR" TEXT,
    "COBRADOR" TEXT,
    "PROVINCIA" TEXT,
    "CIUDAD" TEXT,
    "PARROQUIA" TEXT,
    "FECHA_CREACION" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "clientes_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "cuentas" (
    "ID" SERIAL NOT NULL,
    "FECHA_EMISION" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "VALOR" DOUBLE PRECISION,
    "ESTADO" TEXT,
    "ID_CLIENTE" INTEGER NOT NULL,

    CONSTRAINT "cuentas_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "abonos" (
    "ID" SERIAL NOT NULL,
    "VALOR_ABONO" DOUBLE PRECISION NOT NULL,
    "FECHA_ABONO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODIGO" TEXT NOT NULL,
    "DESCRIPCION" TEXT NOT NULL,
    "ID_CUENTA" INTEGER NOT NULL,

    CONSTRAINT "abonos_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "medidores" (
    "ID" SERIAL NOT NULL,
    "NUMERO_MEDIDOR" TEXT NOT NULL,
    "MODELO" TEXT,
    "MARCA" TEXT,
    "UBICACION" TEXT,
    "FECHA_CREACION" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "ID_CLIENTE" INTEGER NOT NULL,

    CONSTRAINT "medidores_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "detalles_medidor" (
    "ID" SERIAL NOT NULL,
    "ID_MEDIDOR" INTEGER NOT NULL,
    "FECHA_LECTURA" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "LECTURA" TEXT NOT NULL,

    CONSTRAINT "detalles_medidor_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "sucursales" (
    "ID" SERIAL NOT NULL,
    "NOMBRE" TEXT,
    "UBICACION" TEXT,
    "PUNTO_EMISION" TEXT,

    CONSTRAINT "sucursales_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "razones" (
    "ID" SERIAL NOT NULL,
    "CODIGO" TEXT,
    "RAZON" TEXT,
    "PRECIO1" DECIMAL(10,2),
    "PRECIO2" DECIMAL(10,2),
    "IVA" DECIMAL(5,2),

    CONSTRAINT "razones_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "facturas" (
    "ID" SERIAL NOT NULL,
    "SECUENCIA" INTEGER NOT NULL,
    "FECHA_EMISION" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "FECHA_AUTORIZACION" TIMESTAMP(3),
    "ID_SUCURSAL" INTEGER NOT NULL,
    "ID_USUARIO" INTEGER NOT NULL,
    "ID_CLIENTE" INTEGER NOT NULL,
    "ID_MEDIDOR" INTEGER NOT NULL,
    "ESTADO_FACTURA" "ESTADO_FACTURA" DEFAULT 'SIN_AUTORIZAR',
    "TIPO_PAGO" "TIPO_PAGO" NOT NULL,
    "VALOR_SIN_IMPUESTO" DOUBLE PRECISION NOT NULL,
    "IVA" DOUBLE PRECISION NOT NULL,
    "TOTAL" DOUBLE PRECISION NOT NULL,
    "FECHA_VENCIMIENTO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "CLAVE_ACCESO" TEXT,

    CONSTRAINT "facturas_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "detalles_factura" (
    "ID" SERIAL NOT NULL,
    "ID_FACTURA" INTEGER NOT NULL,
    "ID_RAZON" INTEGER NOT NULL,
    "DESCRIPCION" TEXT,
    "SUBTOTAL" DOUBLE PRECISION,
    "DESCUENTO" DOUBLE PRECISION DEFAULT 0,
    "CANTIDAD" INTEGER DEFAULT 1,
    "PRECIO_IVA" DOUBLE PRECISION,

    CONSTRAINT "detalles_factura_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "conceptos" (
    "ID" SERIAL NOT NULL,
    "CODIGO" VARCHAR(32) NOT NULL,
    "COD_INTERNO" VARCHAR(32),
    "DESCRIPCION" VARCHAR(255) NOT NULL,
    "PRECIO_BASE" DECIMAL(10,2),
    "REQUIERE_MES" BOOLEAN NOT NULL DEFAULT false,
    "ESTADO" BOOLEAN NOT NULL DEFAULT true,
    "FECHA_CREACION" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "conceptos_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "liquidacion_compra" (
    "id" SERIAL NOT NULL,
    "fechaEmision" TEXT NOT NULL,
    "dirEstablecimiento" TEXT NOT NULL,
    "tipoIdentificacionProveedor" TEXT NOT NULL,
    "razonSocialProveedor" TEXT NOT NULL,
    "identificacionProveedor" TEXT NOT NULL,
    "totalSinImpuestos" DOUBLE PRECISION NOT NULL,
    "totalDescuento" DOUBLE PRECISION NOT NULL,
    "importeTotal" DOUBLE PRECISION NOT NULL,
    "moneda" TEXT NOT NULL,
    "xml" TEXT,
    "accessKey" TEXT,
    "estadoSri" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "liquidacion_compra_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "detalle_liquidacion" (
    "id" SERIAL NOT NULL,
    "codigoPrincipal" TEXT NOT NULL,
    "descripcion" TEXT NOT NULL,
    "precioUnitario" DOUBLE PRECISION NOT NULL,
    "cantidad" DOUBLE PRECISION NOT NULL,
    "descuento" DOUBLE PRECISION NOT NULL,
    "precioTotalSinImpuesto" DOUBLE PRECISION NOT NULL,
    "codigoImpuesto" TEXT NOT NULL,
    "codigoPorcentajeImpuesto" TEXT NOT NULL,
    "tarifaImpuesto" DOUBLE PRECISION NOT NULL,
    "baseImponible" DOUBLE PRECISION NOT NULL,
    "valorImpuesto" DOUBLE PRECISION NOT NULL,
    "liquidacionId" INTEGER NOT NULL,

    CONSTRAINT "detalle_liquidacion_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "usuarios_CEDULA_key" ON "usuarios"("CEDULA");

-- CreateIndex
CREATE UNIQUE INDEX "usuarios_CORREO_key" ON "usuarios"("CORREO");

-- CreateIndex
CREATE UNIQUE INDEX "clientes_IDENTIFICACION_key" ON "clientes"("IDENTIFICACION");

-- CreateIndex
CREATE INDEX "CUENTAS_ID_CLIENTE_fkey" ON "cuentas"("ID_CLIENTE");

-- CreateIndex
CREATE INDEX "ABONOS_ID_CUENTA_fkey" ON "abonos"("ID_CUENTA");

-- CreateIndex
CREATE UNIQUE INDEX "medidores_NUMERO_MEDIDOR_key" ON "medidores"("NUMERO_MEDIDOR");

-- CreateIndex
CREATE INDEX "MEDIDORES_ID_CLIENTE_fkey" ON "medidores"("ID_CLIENTE");

-- CreateIndex
CREATE INDEX "DETALLES_MEDIDOR_ID_MEDIDOR_fkey" ON "detalles_medidor"("ID_MEDIDOR");

-- CreateIndex
CREATE INDEX "FACTURAS_ID_CLIENTE_fkey" ON "facturas"("ID_CLIENTE");

-- CreateIndex
CREATE INDEX "FACTURAS_ID_MEDIDOR_fkey" ON "facturas"("ID_MEDIDOR");

-- CreateIndex
CREATE INDEX "FACTURAS_ID_SUCURSAL_fkey" ON "facturas"("ID_SUCURSAL");

-- CreateIndex
CREATE INDEX "FACTURAS_ID_USUARIO_fkey" ON "facturas"("ID_USUARIO");

-- CreateIndex
CREATE INDEX "DETALLES_FACTURA_ID_FACTURA_fkey" ON "detalles_factura"("ID_FACTURA");

-- CreateIndex
CREATE INDEX "DETALLES_FACTURA_ID_RAZON_fkey" ON "detalles_factura"("ID_RAZON");

-- CreateIndex
CREATE UNIQUE INDEX "CODIGO" ON "conceptos"("CODIGO");

-- CreateIndex
CREATE INDEX "detalle_liquidacion_liquidacionId_idx" ON "detalle_liquidacion"("liquidacionId");

-- AddForeignKey
ALTER TABLE "cuentas" ADD CONSTRAINT "cuentas_ID_CLIENTE_fkey" FOREIGN KEY ("ID_CLIENTE") REFERENCES "clientes"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "abonos" ADD CONSTRAINT "abonos_ID_CUENTA_fkey" FOREIGN KEY ("ID_CUENTA") REFERENCES "cuentas"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "medidores" ADD CONSTRAINT "medidores_ID_CLIENTE_fkey" FOREIGN KEY ("ID_CLIENTE") REFERENCES "clientes"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "detalles_medidor" ADD CONSTRAINT "detalles_medidor_ID_MEDIDOR_fkey" FOREIGN KEY ("ID_MEDIDOR") REFERENCES "medidores"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "facturas" ADD CONSTRAINT "facturas_ID_CLIENTE_fkey" FOREIGN KEY ("ID_CLIENTE") REFERENCES "clientes"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "facturas" ADD CONSTRAINT "facturas_ID_MEDIDOR_fkey" FOREIGN KEY ("ID_MEDIDOR") REFERENCES "medidores"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "facturas" ADD CONSTRAINT "facturas_ID_SUCURSAL_fkey" FOREIGN KEY ("ID_SUCURSAL") REFERENCES "sucursales"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "facturas" ADD CONSTRAINT "facturas_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "usuarios"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "detalles_factura" ADD CONSTRAINT "detalles_factura_ID_FACTURA_fkey" FOREIGN KEY ("ID_FACTURA") REFERENCES "facturas"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "detalles_factura" ADD CONSTRAINT "detalles_factura_ID_RAZON_fkey" FOREIGN KEY ("ID_RAZON") REFERENCES "razones"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "detalle_liquidacion" ADD CONSTRAINT "detalle_liquidacion_liquidacionId_fkey" FOREIGN KEY ("liquidacionId") REFERENCES "liquidacion_compra"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
