-- CreateTable
CREATE TABLE `USUARIOS` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CEDULA` VARCHAR(191) NOT NULL,
    `NOMBRE` VARCHAR(191) NOT NULL,
    `APELLIDO` VARCHAR(191) NOT NULL,
    `CORREO` VARCHAR(191) NOT NULL,
    `HASH` VARCHAR(191) NOT NULL,
    `SALT` VARCHAR(191) NOT NULL,
    `ROL` ENUM('CONTADOR', 'TESORERO', 'ADMIN') NOT NULL DEFAULT 'CONTADOR',
    `ESTADO` BOOLEAN NOT NULL DEFAULT true,
    `FECHA_CREACION` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `USUARIOS_CEDULA_key`(`CEDULA`),
    UNIQUE INDEX `USUARIOS_CORREO_key`(`CORREO`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CLIENTES` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `IDENTIFICACION` VARCHAR(191) NOT NULL,
    `RAZON_SOCIAL` VARCHAR(191) NOT NULL,
    `NOMBRE_COMERCIAL` VARCHAR(191) NULL,
    `DIRECCION` VARCHAR(191) NOT NULL,
    `TELEFONO1` VARCHAR(191) NOT NULL,
    `TELEFONO2` VARCHAR(191) NULL,
    `CORREO` VARCHAR(191) NULL DEFAULT 'tiolucasoswaldo1967@gmail.com',
    `TARIFA` VARCHAR(191) NULL,
    `GRUPO` VARCHAR(191) NULL,
    `ZONA` VARCHAR(191) NULL,
    `RUTA` VARCHAR(191) NULL,
    `VENDEDOR` VARCHAR(191) NULL,
    `COBRADOR` VARCHAR(191) NULL,
    `PROVINCIA` VARCHAR(191) NULL,
    `CIUDAD` VARCHAR(191) NULL,
    `PARROQUIA` VARCHAR(191) NULL,
    `FECHA_CREACION` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `CLIENTES_IDENTIFICACION_key`(`IDENTIFICACION`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CUENTAS` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `FECHA_EMISION` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `VALOR` DOUBLE NULL,
    `ESTADO` VARCHAR(191) NULL,
    `ID_CLIENTE` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ABONOS` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `VALOR_ABONO` DOUBLE NOT NULL,
    `FECHA_ABONO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CODIGO` VARCHAR(191) NOT NULL,
    `DESCRIPCION` VARCHAR(191) NOT NULL,
    `ID_CUENTA` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MEDIDORES` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NUMERO_MEDIDOR` VARCHAR(191) NOT NULL,
    `MODELO` VARCHAR(191) NULL,
    `MARCA` VARCHAR(191) NULL,
    `UBICACION` VARCHAR(191) NULL,
    `FECHA_CREACION` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ID_CLIENTE` INTEGER NOT NULL,

    UNIQUE INDEX `MEDIDORES_NUMERO_MEDIDOR_key`(`NUMERO_MEDIDOR`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DETALLES_MEDIDOR` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_MEDIDOR` INTEGER NOT NULL,
    `FECHA_LECTURA` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `LECTURA` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SUCURSALES` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NOMBRE` VARCHAR(191) NULL,
    `UBICACION` VARCHAR(191) NULL,
    `PUNTO_EMISION` VARCHAR(191) NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RAZONES` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CODIGO` VARCHAR(191) NULL,
    `RAZON` VARCHAR(191) NULL,
    `PRECIO1` DECIMAL(10, 2) NULL,
    `PRECIO2` DECIMAL(10, 2) NULL,
    `IVA` DECIMAL(5, 2) NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `FACTURAS` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SECUENCIA` INTEGER NOT NULL,
    `FECHA_EMISION` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FECHA_AUTORIZACION` DATETIME(3) NULL,
    `ID_SUCURSAL` INTEGER NOT NULL,
    `ID_USUARIO` INTEGER NOT NULL,
    `ID_CLIENTE` INTEGER NOT NULL,
    `ID_MEDIDOR` INTEGER NOT NULL,
    `ESTADO_FACTURA` ENUM('AUTORIZADO', 'ELIMINADO', 'SIN_AUTORIZAR') NULL DEFAULT 'SIN_AUTORIZAR',
    `TIPO_PAGO` ENUM('EFECTIVO', 'CREDITO', 'DEPOSITO', 'CHEQUE') NOT NULL,
    `VALOR_SIN_IMPUESTO` DOUBLE NOT NULL,
    `IVA` DOUBLE NOT NULL,
    `TOTAL` DOUBLE NOT NULL,
    `FECHA_VENCIMIENTO` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CLAVE_ACCESO` VARCHAR(191) NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DETALLES_FACTURA` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_FACTURA` INTEGER NOT NULL,
    `ID_RAZON` INTEGER NOT NULL,
    `DESCRIPCION` VARCHAR(191) NULL,
    `SUBTOTAL` DOUBLE NULL,
    `DESCUENTO` DOUBLE NULL DEFAULT 0,
    `CANTIDAD` INTEGER NULL DEFAULT 1,
    `PRECIO_IVA` DOUBLE NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `CUENTAS` ADD CONSTRAINT `CUENTAS_ID_CLIENTE_fkey` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTES`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ABONOS` ADD CONSTRAINT `ABONOS_ID_CUENTA_fkey` FOREIGN KEY (`ID_CUENTA`) REFERENCES `CUENTAS`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MEDIDORES` ADD CONSTRAINT `MEDIDORES_ID_CLIENTE_fkey` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTES`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DETALLES_MEDIDOR` ADD CONSTRAINT `DETALLES_MEDIDOR_ID_MEDIDOR_fkey` FOREIGN KEY (`ID_MEDIDOR`) REFERENCES `MEDIDORES`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FACTURAS` ADD CONSTRAINT `FACTURAS_ID_SUCURSAL_fkey` FOREIGN KEY (`ID_SUCURSAL`) REFERENCES `SUCURSALES`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FACTURAS` ADD CONSTRAINT `FACTURAS_ID_USUARIO_fkey` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIOS`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FACTURAS` ADD CONSTRAINT `FACTURAS_ID_CLIENTE_fkey` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTES`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FACTURAS` ADD CONSTRAINT `FACTURAS_ID_MEDIDOR_fkey` FOREIGN KEY (`ID_MEDIDOR`) REFERENCES `MEDIDORES`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DETALLES_FACTURA` ADD CONSTRAINT `DETALLES_FACTURA_ID_FACTURA_fkey` FOREIGN KEY (`ID_FACTURA`) REFERENCES `FACTURAS`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DETALLES_FACTURA` ADD CONSTRAINT `DETALLES_FACTURA_ID_RAZON_fkey` FOREIGN KEY (`ID_RAZON`) REFERENCES `RAZONES`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
